name: flowers_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter_18pt-Bold.ttf
      - asset: assets/fonts/Inter_18pt-Medium.ttf
      - asset: assets/fonts/Inter_18pt-Regular.ttf
      - asset: assets/fonts/Inter_18pt-SemiBold.ttf
      - asset: assets/fonts/Inter_24pt-Bold.ttf
      - asset: assets/fonts/Inter_24pt-Medium.ttf
      - asset: assets/fonts/Inter_24pt-Regular.ttf
      - asset: assets/fonts/Inter_24pt-SemiBold.ttf
      - asset: assets/fonts/Inter_28pt-Bold.ttf
      - asset: assets/fonts/Inter_28pt-Medium.ttf
      - asset: assets/fonts/Inter_28pt-Regular.ttf
      - asset: assets/fonts/Inter_28pt-SemiBold.ttf